[project]
name = "mini-dust3r"
version = "0.1.0"
description = "Add a short description here"
authors = ["pablovela5620 <pablovela5620@gmail.com>"]
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64"]

[system-requirements]
libc = { family="glibc", version="2.30" }

[tasks]
build-croco = { cmd = "python setup.py build_ext --inplace", cwd = "mini_dust3r/croco/curope/", outputs=["lib.linux-x86_64-cpython-311/curope.cpython-311-x86_64-linux-gnu.so"]}
download-checkpoint = {cmd = "ls checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth || wget -P checkpoints/ https://download.europe.naverlabs.com/ComputerVision/DUSt3R/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth", outputs=["checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth"]}
post-install = { cmd = "pwd", depends_on = ["download-checkpoint", "build-croco"]}
demo = "python demo.py --weights checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth"


[dependencies]
python = "3.11.*"
pip = ">=23.3.2,<23.4"
cuda = {version = "*", channel="nvidia/label/cuda-11.8.0"}
pytorch-cuda = {version = "11.8.*", channel="pytorch"}
pytorch = {version = ">=2.2.0,<2.3", channel="pytorch"}
torchvision = {version = ">=0.17.0,<0.18", channel="pytorch"}
cmake = "3.14.0.*"
matplotlib = ">=3.8.3,<3.9"
einops = ">=0.7.0,<0.8"
tqdm = ">=4.66.2,<4.67"
scipy = ">=1.12.0,<1.13"
trimesh = ">=4.2.0,<4.3"
tensorboard = ">=2.16.2,<2.17"
pyglet = ">=1.5.27,<1.6"
rerun-sdk = ">=0.14.1,<0.15"
jaxtyping = ">=0.2.28,<0.3"
gradio = ">=4.29.0,<4.30"

[pypi-dependencies]
roma = "*"
opencv-python = "*"
mini-dust3r = { path = ".", editable = true}
gradio-rerun = "*"
open3d = "*"

